name: E2E Tests
on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  lint: 
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v4
          with:
            node-version: 22
        - run: npm ci
        - run: npm run eslint
    
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          start: npm run start
          wait-on: 'http://localhost:3000'
          config: >
           "chromeWebSecurity=false,video=false,reporter=mochawesome,reporterOptions=
           '{\"reportDir\":\"cypress/reports\",\"overwrite\":false,\"html\":true,\"json\":true}'"

      - name: Run Lighthouse Tests
        if: always()  
        run: |
          npm run lighthouse

      - name: Combine reports
        if: always() 
        run: |
          npx mochawesome-merge "cypress/reports/*.json" --output cypress/reports/final-report.json
      
      - name: Merge Mochawesome reports
        if: always() 
        run: |
          npx marge cypress/reports/final-report.json -f final-report -o cypress/reports --inline 

      - name: Upload Cypress report
        if: always() 
        uses: actions/upload-artifact@v4
        with:
          name: cypress-report
          path: cypress/reports/final-report.html
          retention-days: 7
      
      - name: Upload Lighthouse report
        if: always() 
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-report
          path: cypress/reports/lh-report.html
          retention-days: 7

      - name: Send Email with Reports

        if: always()

        uses: dawidd6/action-send-mail@v3

        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASSWORD }}
          secure: true
          subject: "Cypress Report - Run #${{ github.run_number }}"
          to: ${{ secrets.TO_EMAIL }}
          from: Cypress QA Bot <${{ secrets.SMTP_USER }}>
          body: |
            Reports from the latest GitHub run:
            • Cypress Report: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
            • Lighthouse Report: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
            You can download the full artifacts from the "Artifacts" section of the workflow run.
          attachments: |
            cypress/reports/final-report.html
            cypress/reports/lh-report.html

      - name: Clean reports even if earlier steps failed
        run: |
          rm -rf cypress/reports/* || true
        if: always()